#错误处理
我们可以使用两个函数：assert 和 error 来处理错误。实例如下：
```lua
local function add(a,b)
   assert(type(a) == "number", "a 不是一个数字")
   assert(type(b) == "number", "b 不是一个数字")
   return a+b
end
add(10)

```

##error函数

语法格式：
error (message [, level])
功能：终止正在执行的函数，并返回message的内容作为错误信息(error函数永远都不会返回)

通常情况下，error会附加一些错误位置的信息到message头部。

Level参数指示获得错误的位置:
* Level=1[默认]：为调用error位置(文件+行号)
* Level=2：指出哪个调用error的函数的函数
* Level=0:不添加错误位置信息

##pcall 和 xpcall、debug
语法格式如下 
```lua
if pcall(function_name, ….) then
-- 没有错误
else
-- 一些错误
end

```
pcall以一种"保护模式"来调用第一个参数，因此pcall可以捕获函数执行中的任何错误。

通常在错误发生时，希望落得更多的调试信息，而不只是发生错误的位置。但pcall返回时，它已经销毁了调用桟的部分内容。

Lua提供了xpcall函数，xpcall接收第二个参数——一个错误处理函数，当错误发生时，Lua会在调用桟展看（unwind）前调用错误处理函数，于是就可以在这个函数中使用debug库来获取关于错误的额外信息了。

debug库提供了两个通用的错误处理函数:
* debug.debug：提供一个Lua提示符，让用户来价差错误的原因
* debug.traceback：根据调用桟来构建一个扩展的错误消息

xpcall 使用实例 2: 
```lua
function myfunction ()
   n = n/nil
end
function myerrorhandler( err )
    print( "ERROR:", err )
    --print(debug.debug())
    print(debug.traceback())
end

status = xpcall( myfunction, myerrorhandler )
print( status)

```